import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Providers from './Providers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Book Management System',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`overflow-y-scroll ${geistSans.variable} ${geistMono.variable} antialiased`}>
          <nav className="fixed top-0 z-50 w-full bg-white shadow-md">
            <div className="container mx-auto flex h-16 items-center justify-between px-4">
              <div className="flex items-center">
                <h1 className="text-2xl font-bold">Book Management System</h1>
              </div>
            </div>
          </nav>

          {children}
          <Toaster />
        </body>
      </Providers>
    </html>
  )
}
